// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tcsoft_pingpongclub.Models;

#nullable disable

namespace tcsoft_pingpongclub.Migrations
{
    [DbContext(typeof(ThuctapKtktcn2024Context))]
    [Migration("20250102084041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Award", b =>
                {
                    b.Property<int>("IdAward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAward");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAward"));

                    b.Property<short?>("IOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("iOrder");

                    b.Property<int?>("IdTournament")
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    b.Property<decimal?>("Money")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("money");

                    b.Property<short?>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdAward")
                        .HasName("PK_Award_idAward");

                    b.HasIndex("IdTournament");

                    b.ToTable("Award", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.ExpenseAndIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("DaysOverdue")
                        .HasColumnType("smallint")
                        .HasColumnName("daysOverdue");

                    b.Property<int?>("IdAccountant")
                        .HasColumnType("int")
                        .HasColumnName("idAccountant");

                    b.Property<int?>("IdFund")
                        .HasColumnType("int")
                        .HasColumnName("idFund");

                    b.Property<int?>("IdParty")
                        .HasColumnType("int")
                        .HasColumnName("idParty");

                    b.Property<int?>("IdReason")
                        .HasColumnType("int")
                        .HasColumnName("idReason");

                    b.Property<bool?>("IsDone")
                        .HasColumnType("bit")
                        .HasColumnName("isDone");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<bool?>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk");

                    b.HasIndex("IdFund");

                    b.HasIndex("IdParty");

                    b.HasIndex("IdReason");

                    b.ToTable("ExpenseAndIncome", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Fund", b =>
                {
                    b.Property<int>("IdFund")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFund");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFund"));

                    b.Property<string>("FundName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fundName");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdFund")
                        .HasName("pk1");

                    b.ToTable("Fund", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Groupstage", b =>
                {
                    b.Property<int>("IdGroupstage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGroupstage");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroupstage"));

                    b.Property<int?>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<short?>("IOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("iOrder");

                    b.Property<int?>("IdTournament")
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    b.Property<string>("NameGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nameGroup");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdGroupstage")
                        .HasName("pkRound");

                    b.HasIndex("IdTournament");

                    b.ToTable("Groupstage", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.HadicapTable", b =>
                {
                    b.Property<int>("IdHadicap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idHadicap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHadicap"));

                    b.Property<short?>("Hadicap")
                        .HasColumnType("smallint")
                        .HasColumnName("hadicap");

                    b.Property<int?>("IdHighLevel")
                        .HasColumnType("int")
                        .HasColumnName("idHighLevel");

                    b.Property<int?>("IdLowLevel")
                        .HasColumnType("int")
                        .HasColumnName("idLowLevel");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdHadicap")
                        .HasName("pkHadicap");

                    b.HasIndex("IdHighLevel");

                    b.HasIndex("IdLowLevel");

                    b.ToTable("HadicapTable", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Level", b =>
                {
                    b.Property<int>("IdLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idLevel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLevel"));

                    b.Property<string>("LevelName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("levelName");

                    b.Property<int?>("ScoreEnd")
                        .HasColumnType("int")
                        .HasColumnName("scoreEnd");

                    b.Property<int?>("ScoreStart")
                        .HasColumnType("int")
                        .HasColumnName("scoreStart");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdLevel")
                        .HasName("pk3");

                    b.ToTable("Level", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Match", b =>
                {
                    b.Property<int>("IdMatch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMatch");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatch"));

                    b.Property<int?>("IdGroupstage")
                        .HasColumnType("int")
                        .HasColumnName("idGroupstage");

                    b.Property<int?>("IdMemberOne")
                        .HasColumnType("int")
                        .HasColumnName("idMemberOne");

                    b.Property<int?>("IdMemberTwo")
                        .HasColumnType("int")
                        .HasColumnName("idMemberTwo");

                    b.Property<int?>("IdMemberWin")
                        .HasColumnType("int")
                        .HasColumnName("idMemberWin");

                    b.Property<int?>("IdTournament")
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime")
                        .HasColumnName("timeStart");

                    b.HasKey("IdMatch")
                        .HasName("pkMatch");

                    b.HasIndex("IdGroupstage");

                    b.HasIndex("IdMemberOne");

                    b.HasIndex("IdMemberTwo");

                    b.HasIndex("IdMemberWin");

                    b.HasIndex("IdTournament");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Member", b =>
                {
                    b.Property<int>("IdMember")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idMember");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMember"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("Emaill")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("emaill");

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<int?>("IdLevel")
                        .HasColumnType("int")
                        .HasColumnName("idLevel");

                    b.Property<int?>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    b.Property<string>("LinkAvatar")
                        .HasColumnType("text")
                        .HasColumnName("linkAvatar");

                    b.Property<string>("MemberName")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)")
                        .HasColumnName("memberName");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("phone");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("IdMember")
                        .HasName("pkMember");

                    b.HasIndex("IdLevel");

                    b.HasIndex("IdRole");

                    b.HasIndex(new[] { "Username" }, "constraint_name1")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("Member", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.NhaTaiTro", b =>
                {
                    b.Property<int>("IdSponor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSponor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSponor"));

                    b.Property<string>("NameSponer")
                        .HasColumnType("text")
                        .HasColumnName("nameSponer");

                    b.Property<string>("UrlLogo")
                        .HasColumnType("text")
                        .HasColumnName("urlLogo");

                    b.HasKey("IdSponor")
                        .HasName("PKidSponor");

                    b.ToTable("NhaTaiTro", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Permission", b =>
                {
                    b.Property<int>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPermission");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermission"));

                    b.Property<string>("NamePermission")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("namePermission");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Url")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("url");

                    b.HasKey("IdPermission")
                        .HasName("pkPermission");

                    b.ToTable("Permission", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.PermissionRole", b =>
                {
                    b.Property<int>("IdPerRo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPerRo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerRo"));

                    b.Property<int>("IdPermission")
                        .HasColumnType("int")
                        .HasColumnName("idPermission");

                    b.Property<int>("IdRole")
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdPerRo")
                        .HasName("pkPerRo");

                    b.HasIndex("IdPermission");

                    b.HasIndex("IdRole");

                    b.ToTable("Permission_Role", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Player", b =>
                {
                    b.Property<int>("IdPlayer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPlayer");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlayer"));

                    b.Property<int>("IdMember")
                        .HasColumnType("int")
                        .HasColumnName("idMember");

                    b.Property<int>("IdTournament")
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    b.Property<short?>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdPlayer")
                        .HasName("pkPlayer");

                    b.HasIndex("IdMember");

                    b.HasIndex("IdTournament");

                    b.ToTable("Player", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Reason", b =>
                {
                    b.Property<int>("IdReason")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idReason");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReason"));

                    b.Property<string>("ReasonName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reasonName");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<bool?>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("type");

                    b.HasKey("IdReason")
                        .HasName("pkReason");

                    b.ToTable("Reason", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRole");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRole"));

                    b.Property<string>("NameRole")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nameRole");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdRole")
                        .HasName("pkRole");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.ScoreCal", b =>
                {
                    b.Property<int>("IdScoreCal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idScoreCal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdScoreCal"));

                    b.Property<short?>("PtsHighRankDef")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsHighRankDef");

                    b.Property<short?>("PtsHighRankWin")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsHighRankWin");

                    b.Property<short?>("PtsMax")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsMax");

                    b.Property<short?>("PtsMin")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsMin");

                    b.Property<short?>("PtsSameRankDef")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsSameRankDef");

                    b.Property<short?>("PtsSameRankWin")
                        .HasColumnType("smallint")
                        .HasColumnName("ptsSameRankWin");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdScoreCal")
                        .HasName("pkScoreCal");

                    b.ToTable("ScoreCal", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Set", b =>
                {
                    b.Property<int>("IdSet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSet"));

                    b.Property<int>("IdMatch")
                        .HasColumnType("int")
                        .HasColumnName("idMatch");

                    b.Property<int>("IdWinner")
                        .HasColumnType("int")
                        .HasColumnName("idWinner");

                    b.Property<string>("Ratio")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ratio");

                    b.Property<string>("SetName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("setName");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("timeEnd");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime")
                        .HasColumnName("timeStart");

                    b.HasKey("IdSet")
                        .HasName("pkSet");

                    b.HasIndex("IdMatch");

                    b.ToTable("Set", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Sponor", b =>
                {
                    b.Property<int>("IdSponorTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idSponorTour");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSponorTour"));

                    b.Property<int?>("IdIncome")
                        .HasColumnType("int")
                        .HasColumnName("idIncome");

                    b.Property<int?>("IdSponor")
                        .HasColumnType("int")
                        .HasColumnName("idSponor");

                    b.Property<int?>("IdTournament")
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    b.Property<decimal?>("Money")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("money");

                    b.Property<string>("Other")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("other");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.HasKey("IdSponorTour")
                        .HasName("pkSponor");

                    b.HasIndex("IdIncome");

                    b.HasIndex("IdSponor");

                    b.HasIndex("IdTournament");

                    b.ToTable("Sponor", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Tournament", b =>
                {
                    b.Property<int>("IdTournament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTournament");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTournament"));

                    b.Property<short?>("Amount")
                        .HasColumnType("smallint")
                        .HasColumnName("amount");

                    b.Property<string>("Infor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RankEnd")
                        .HasColumnType("int")
                        .HasColumnName("rankEnd");

                    b.Property<int?>("RankStart")
                        .HasColumnType("int")
                        .HasColumnName("rankStart");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("datetime")
                        .HasColumnName("timeEnd");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime")
                        .HasColumnName("timeStart");

                    b.Property<string>("TournamentName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tournamentName");

                    b.Property<bool?>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("type");

                    b.Property<string>("UrlImage")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("urlImage");

                    b.HasKey("IdTournament")
                        .HasName("pkidTournament");

                    b.HasIndex("RankEnd");

                    b.HasIndex("RankStart");

                    b.ToTable("Tournament", (string)null);
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Award", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Tournament", "IdTournamentNavigation")
                        .WithMany("Awards")
                        .HasForeignKey("IdTournament")
                        .HasConstraintName("FK_Award_Tournament");

                    b.Navigation("IdTournamentNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.ExpenseAndIncome", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Fund", "IdFundNavigation")
                        .WithMany("ExpenseAndIncomes")
                        .HasForeignKey("IdFund")
                        .HasConstraintName("FK_ExpenseAndIncome_Fund");

                    b.HasOne("tcsoft_pingpongclub.Models.Member", "IdPartyNavigation")
                        .WithMany("ExpenseAndIncomes")
                        .HasForeignKey("IdParty")
                        .HasConstraintName("FK_ExpenseAndIncome_Member");

                    b.HasOne("tcsoft_pingpongclub.Models.Reason", "IdReasonNavigation")
                        .WithMany("ExpenseAndIncomes")
                        .HasForeignKey("IdReason")
                        .HasConstraintName("FK_ExpenseAndIncome_Reason");

                    b.Navigation("IdFundNavigation");

                    b.Navigation("IdPartyNavigation");

                    b.Navigation("IdReasonNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Groupstage", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Tournament", "IdTournamentNavigation")
                        .WithMany("Groupstages")
                        .HasForeignKey("IdTournament")
                        .HasConstraintName("FK_Groupstage_Tournament");

                    b.Navigation("IdTournamentNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.HadicapTable", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Level", "IdHighLevelNavigation")
                        .WithMany("HadicapTableIdHighLevelNavigations")
                        .HasForeignKey("IdHighLevel")
                        .HasConstraintName("FK_HadicapTable_Level");

                    b.HasOne("tcsoft_pingpongclub.Models.Level", "IdLowLevelNavigation")
                        .WithMany("HadicapTableIdLowLevelNavigations")
                        .HasForeignKey("IdLowLevel")
                        .HasConstraintName("FK_HadicapTable_Level1");

                    b.Navigation("IdHighLevelNavigation");

                    b.Navigation("IdLowLevelNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Match", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Groupstage", "IdGroupstageNavigation")
                        .WithMany("Matches")
                        .HasForeignKey("IdGroupstage")
                        .HasConstraintName("FK_Match_Groupstage");

                    b.HasOne("tcsoft_pingpongclub.Models.Player", "IdMemberOneNavigation")
                        .WithMany("MatchIdMemberOneNavigations")
                        .HasForeignKey("IdMemberOne")
                        .HasConstraintName("FK_Match_Player");

                    b.HasOne("tcsoft_pingpongclub.Models.Player", "IdMemberTwoNavigation")
                        .WithMany("MatchIdMemberTwoNavigations")
                        .HasForeignKey("IdMemberTwo")
                        .HasConstraintName("FK_Match_Player1");

                    b.HasOne("tcsoft_pingpongclub.Models.Player", "IdMemberWinNavigation")
                        .WithMany("MatchIdMemberWinNavigations")
                        .HasForeignKey("IdMemberWin")
                        .HasConstraintName("FK_Match_Player2");

                    b.HasOne("tcsoft_pingpongclub.Models.Tournament", "IdTournamentNavigation")
                        .WithMany("Matches")
                        .HasForeignKey("IdTournament")
                        .HasConstraintName("FK_Match_Tournament");

                    b.Navigation("IdGroupstageNavigation");

                    b.Navigation("IdMemberOneNavigation");

                    b.Navigation("IdMemberTwoNavigation");

                    b.Navigation("IdMemberWinNavigation");

                    b.Navigation("IdTournamentNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Member", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Level", "IdLevelNavigation")
                        .WithMany("Members")
                        .HasForeignKey("IdLevel")
                        .HasConstraintName("FK_Member_Level");

                    b.HasOne("tcsoft_pingpongclub.Models.Role", "IdRoleNavigation")
                        .WithMany("Members")
                        .HasForeignKey("IdRole")
                        .HasConstraintName("FK_Member_Role");

                    b.Navigation("IdLevelNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.PermissionRole", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Permission", "IdPermissionNavigation")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("IdPermission")
                        .IsRequired()
                        .HasConstraintName("FK_Permission_Role_Permission");

                    b.HasOne("tcsoft_pingpongclub.Models.Role", "IdRoleNavigation")
                        .WithMany("PermissionRoles")
                        .HasForeignKey("IdRole")
                        .IsRequired()
                        .HasConstraintName("FK_Permission_Role_Role");

                    b.Navigation("IdPermissionNavigation");

                    b.Navigation("IdRoleNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Player", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Member", "IdMemberNavigation")
                        .WithMany("Players")
                        .HasForeignKey("IdMember")
                        .IsRequired()
                        .HasConstraintName("FK_Player_Member");

                    b.HasOne("tcsoft_pingpongclub.Models.Tournament", "IdTournamentNavigation")
                        .WithMany("Players")
                        .HasForeignKey("IdTournament")
                        .IsRequired()
                        .HasConstraintName("FK_Player_Tournament");

                    b.Navigation("IdMemberNavigation");

                    b.Navigation("IdTournamentNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Set", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Match", "IdMatchNavigation")
                        .WithMany("Sets")
                        .HasForeignKey("IdMatch")
                        .IsRequired()
                        .HasConstraintName("FK_Set_Match");

                    b.Navigation("IdMatchNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Sponor", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.ExpenseAndIncome", "IdIncomeNavigation")
                        .WithMany("Sponors")
                        .HasForeignKey("IdIncome")
                        .HasConstraintName("FK_Sponor_ExpenseAndIncome");

                    b.HasOne("tcsoft_pingpongclub.Models.NhaTaiTro", "IdSponorNavigation")
                        .WithMany("Sponors")
                        .HasForeignKey("IdSponor")
                        .HasConstraintName("FK_Sponor_NhaTaiTro");

                    b.HasOne("tcsoft_pingpongclub.Models.Tournament", "IdTournamentNavigation")
                        .WithMany("Sponors")
                        .HasForeignKey("IdTournament")
                        .HasConstraintName("FK_Sponor_Tournament");

                    b.Navigation("IdIncomeNavigation");

                    b.Navigation("IdSponorNavigation");

                    b.Navigation("IdTournamentNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Tournament", b =>
                {
                    b.HasOne("tcsoft_pingpongclub.Models.Level", "RankEndNavigation")
                        .WithMany("TournamentRankEndNavigations")
                        .HasForeignKey("RankEnd")
                        .HasConstraintName("FK_Tournament_Level1");

                    b.HasOne("tcsoft_pingpongclub.Models.Level", "RankStartNavigation")
                        .WithMany("TournamentRankStartNavigations")
                        .HasForeignKey("RankStart")
                        .HasConstraintName("FK_Tournament_Level");

                    b.Navigation("RankEndNavigation");

                    b.Navigation("RankStartNavigation");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.ExpenseAndIncome", b =>
                {
                    b.Navigation("Sponors");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Fund", b =>
                {
                    b.Navigation("ExpenseAndIncomes");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Groupstage", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Level", b =>
                {
                    b.Navigation("HadicapTableIdHighLevelNavigations");

                    b.Navigation("HadicapTableIdLowLevelNavigations");

                    b.Navigation("Members");

                    b.Navigation("TournamentRankEndNavigations");

                    b.Navigation("TournamentRankStartNavigations");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Match", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Member", b =>
                {
                    b.Navigation("ExpenseAndIncomes");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.NhaTaiTro", b =>
                {
                    b.Navigation("Sponors");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Permission", b =>
                {
                    b.Navigation("PermissionRoles");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Player", b =>
                {
                    b.Navigation("MatchIdMemberOneNavigations");

                    b.Navigation("MatchIdMemberTwoNavigations");

                    b.Navigation("MatchIdMemberWinNavigations");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Reason", b =>
                {
                    b.Navigation("ExpenseAndIncomes");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Role", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PermissionRoles");
                });

            modelBuilder.Entity("tcsoft_pingpongclub.Models.Tournament", b =>
                {
                    b.Navigation("Awards");

                    b.Navigation("Groupstages");

                    b.Navigation("Matches");

                    b.Navigation("Players");

                    b.Navigation("Sponors");
                });
#pragma warning restore 612, 618
        }
    }
}
